import Head from "next/head";
import AppRight from "../components/AppRight";

export default function Home() {
  return (
    <div className="flex sm:flex-row flex-col-reverse">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div
        style={{
          background:
            "url(https://images.unsplash.com/photo-1476514525535-07fb3b4ae5f1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8NXx8dHJhdmVsJTIwaW4lMjAlMjBuYXR1cmV8ZW58MHx8MHx8&auto=format&fit=crop&w=1000&q=60)",
          flex: "0.6",
        }}
        className="font-poppins flex flex-col h-screen justify-center items-center !bg-cover !bg-bottom object-contain rounded-r-3xl"
      >
        <h2 className="absolute top-10 left-10 text-2xl font-bold  text-white">
          TooTravel
        </h2>
        <div className="flex flex-col w-3/5">
          <h1 className="text-white text-5xl font-semibold ">
            The most beautiful places in the world!
          </h1>
          <p className="text-white text-sm mt-10">
            Plan your vacation on tne most beautiful places in the world
          </p>
          <button className="bg-orange w-60 text-white py-2 h-10 mt-10 px-5 rounded-xl">
            Get Started
          </button>
        </div>
        <div className="absolute bottom-10 left-40 flex items-center ">
          <p className="text-white">01</p>
          <div className="h-[2px] w-10 bg-white ml-2 mr-2"></div>
          <div className="h-[2px] w-10 bg-white mr-2 bg-opacity-20"></div>
          <div className="h-[2px] w-10 bg-white mr-2 bg-opacity-20"></div>
          <p className="text-white">03</p>
        </div>
        <div className="sm:absolute hidden bg-white h-10 w-1 rounded-full mr-1 top-[50vh] left-[58%]"></div>
      </div>
      <div style={{ flex: "0.4" }}>
        <AppRight />
      </div>
    </div>
  );
}
